apiVersion: v1
kind: Service
metadata:
  name: koss
  namespace: default
spec:
  ports:
  - port: 8443
    protocol: TCP
  type: ExternalName
  externalName: 1.1.1.1
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.koss.invidian.github.io
spec:
  group: koss.invidian.github.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: koss
    namespace: default
    port: 8443
  version: v1alpha1
  versionPriority: 100
